// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Context
{
    public partial class CampaignLabel
    {
        public int LabelId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
    }
}