// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Context.Model
{
    public partial class campaign_label_find_udfResult
    {
        public int RowNumber { get; set; }
        public int LabelId { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string CategoryName { get; set; }
    }
}
