// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Context.Model
{
    public partial class campaign_label_find_spResult
    {
        public long? RowNumber { get; set; }
        public int LabelID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string CategoryName { get; set; }
    }
}
